import test from "node:test";
import assert from "node:assert/strict";
import { createApiHandler } from "../server/index.mjs";
import { createGroqClient } from "../server/groq-client.mjs";
import { normalizeGeneratedJourney } from "../src/lib/ai-contract.mjs";

const sample = { summary: { headline: "Make a clear plan", context: ["A new decision", "Wants a broader view"] }, recommendedRole: "Financial adviser", pathway: [{ order: 1, professional: "Financial adviser", reason: "Clarify goals and priorities.", timing: "Start this month", completion: "You have useful questions ready." }], matches: ["Maya Chen", "Luca Singh", "Asha Patel"].map((name, i) => ({ name, speciality: ["Planning", "Property readiness", "Cash-flow clarity"][i], specialities: ["Planning"], consultationMinutes: 60, priceAud: 200 + i * 20, availability: "Tuesday 10:30 am", locations: ["Online"], rationale: "A useful starting conversation for your situation." })) };
const input = { situation: "I am thinking about buying a home." };
function request(handler, { method = "POST", url = "/api/generate", body = input, headers = { "content-type": "application/json", origin: "http://localhost:4321" } } = {}) { const req = { method, url, headers, async *[Symbol.asyncIterator]() { if (body !== undefined) yield Buffer.from(typeof body === "string" ? body : JSON.stringify(body)); } }; let output; const res = { writeHead(code, responseHeaders) { output = { status: code, headers: responseHeaders }; }, end(value) { output.body = JSON.parse(value); } }; return handler(req, res).then(() => output); }
test("successful mocked clarify and generate", async () => { const handler = createApiHandler({ client: { clarify: async () => ({ status: "ready", question: null }), generate: async () => sample } }); assert.equal((await request(handler, { url: "/api/clarify", body: input })).status, 200); const result = await request(handler); assert.equal(result.status, 200); assert.equal(result.body.matches.length, 3); });
test("rejects unsupported method, origin, body and malformed request", async () => { const handler = createApiHandler({ client: { generate: async () => sample } }); assert.equal((await request(handler, { method: "GET" })).status, 405); assert.equal((await request(handler, { headers: { "content-type": "application/json", origin: "https://evil.example" } })).status, 403); assert.equal((await request(handler, { body: { situation: "short" } })).status, 400); assert.equal((await request(handler, { headers: { origin: "http://localhost:4321" } })).status, 415); });
test("maps timeout, provider failures and invalid schema safely", async () => { for (const error of [{ code: "AI_TIMEOUT" }, { code: "AI_UNAVAILABLE" }, { code: "AI_INVALID_RESPONSE" }]) { const result = await request(createApiHandler({ client: { generate: async () => { throw error; } } })); assert.equal(result.status, 502); assert.equal(result.body.code, error.code); assert.equal(result.body.message.includes("raw"), false); } });
test("normalises ids, initials, labels, accents and prices", () => { const result = normalizeGeneratedJourney(sample); assert.deepEqual(result.matches.map((x) => [x.id, x.initials, x.priceLabel, x.availabilityRank]), [["maya-chen", "MC", "$200 / 60 min", 1], ["luca-singh", "LS", "$220 / 60 min", 2], ["asha-patel", "AP", "$240 / 60 min", 3]]); });

const groqResponse = (value) => ({ ok: true, async json() { return { choices: [{ message: { content: JSON.stringify(value) } }] }; } });
test("Groq client sends strict low-reasoning requests and accepts mocked clarification", async () => {
  const calls = []; const client = createGroqClient({ apiKey: "test-key", sleep: async () => {}, fetchImpl: async (url, options) => { calls.push({ url, options }); return groqResponse({ status: "ready", question: null }); } });
  assert.deepEqual(await client.clarify(input.situation), { status: "ready", question: null }); const payload = JSON.parse(calls[0].options.body); assert.equal(payload.model, "openai/gpt-oss-120b"); assert.equal(payload.reasoning_effort, "low"); assert.equal(payload.max_tokens, 200); assert.equal(payload.response_format.type, "json_schema"); assert.equal(payload.response_format.json_schema.strict, true); assert.match(calls[0].options.headers.Authorization, /^Bearer test-key$/);
});
test("Groq client retries exactly once for 429, 5xx, network and invalid structured output, but not permanent HTTP errors", async () => {
  for (const first of [{ ok: false, status: 429 }, { ok: false, status: 503 }, new TypeError("network"), groqResponse({ status: "bad", question: "two. sentences." })]) {
    let calls = 0; const client = createGroqClient({ apiKey: "x", sleep: async () => {}, fetchImpl: async () => { calls += 1; if (calls === 1) { if (first instanceof Error) throw first; return first; } return groqResponse({ status: "ready", question: null }); } }); await client.clarify(input.situation); assert.equal(calls, 2);
  }
  let calls = 0; const client = createGroqClient({ apiKey: "x", sleep: async () => {}, fetchImpl: async () => { calls += 1; return { ok: false, status: 401, async json() { return {}; } }; } }); await assert.rejects(client.clarify(input.situation), (error) => error.code === "AI_UNAVAILABLE"); assert.equal(calls, 1);
});
test("Groq client retries timeout once and exposes a stable timeout code", async () => { let calls = 0; const client = createGroqClient({ apiKey: "x", timeoutMs: 1, sleep: async () => {}, fetchImpl: async (_url, { signal }) => { calls += 1; await new Promise((resolve, reject) => { if (signal.aborted) reject(Object.assign(new Error("aborted"), { name: "AbortError" })); else signal.addEventListener("abort", () => reject(Object.assign(new Error("aborted"), { name: "AbortError" }))); }); } }); await assert.rejects(client.clarify(input.situation), (error) => error.code === "AI_TIMEOUT"); assert.equal(calls, 2); });
