import test from "node:test";
import assert from "node:assert/strict";
import { createApiHandler } from "../server/index.mjs";
import { normalizeGeneratedJourney } from "../src/lib/ai-contract.mjs";

const sample = { summary: { headline: "Make a clear plan", context: ["A new decision", "Wants a broader view"] }, recommendedRole: "Financial adviser", pathway: [{ order: 1, professional: "Financial adviser", reason: "Clarify goals and priorities.", timing: "Start this month", completion: "You have useful questions ready." }], matches: ["Maya Chen", "Luca Singh", "Asha Patel"].map((name, i) => ({ name, speciality: ["Planning", "Property readiness", "Cash-flow clarity"][i], specialities: ["Planning"], consultationMinutes: 60, priceAud: 200 + i * 20, availability: "Tuesday 10:30 am", locations: ["Online"], rationale: "A useful starting conversation for your situation." })) };
const input = { situation: "I am thinking about buying a home." };
function request(handler, { method = "POST", url = "/api/generate", body = input, headers = { "content-type": "application/json", origin: "http://localhost:4321" } } = {}) { const req = { method, url, headers, async *[Symbol.asyncIterator]() { if (body !== undefined) yield Buffer.from(typeof body === "string" ? body : JSON.stringify(body)); } }; let output; const res = { writeHead(code, responseHeaders) { output = { status: code, headers: responseHeaders }; }, end(value) { output.body = JSON.parse(value); } }; return handler(req, res).then(() => output); }
test("successful mocked clarify and generate", async () => { const handler = createApiHandler({ client: { clarify: async () => ({ status: "ready", question: null }), generate: async () => sample } }); assert.equal((await request(handler, { url: "/api/clarify", body: input })).status, 200); const result = await request(handler); assert.equal(result.status, 200); assert.equal(result.body.matches.length, 3); });
test("rejects unsupported method, origin, body and malformed request", async () => { const handler = createApiHandler({ client: { generate: async () => sample } }); assert.equal((await request(handler, { method: "GET" })).status, 405); assert.equal((await request(handler, { headers: { "content-type": "application/json", origin: "https://evil.example" } })).status, 403); assert.equal((await request(handler, { body: { situation: "short" } })).status, 400); assert.equal((await request(handler, { headers: { origin: "http://localhost:4321" } })).status, 415); });
test("maps timeout, provider failures and invalid schema safely", async () => { for (const error of [{ code: "AI_TIMEOUT" }, { code: "AI_UNAVAILABLE" }, { code: "AI_INVALID_RESPONSE" }]) { const result = await request(createApiHandler({ client: { generate: async () => { throw error; } } })); assert.equal(result.status, 502); assert.equal(result.body.code, error.code); assert.equal(result.body.message.includes("raw"), false); } });
test("normalises ids, initials, labels, accents and prices", () => { const result = normalizeGeneratedJourney(sample); assert.deepEqual(result.matches.map((x) => [x.id, x.initials, x.priceLabel, x.availabilityRank]), [["maya-chen", "MC", "$200 / 60 min", 1], ["luca-singh", "LS", "$220 / 60 min", 2], ["asha-patel", "AP", "$240 / 60 min", 3]]); });
